# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a90ecf7443c2d610348ecab90edd97a92f80d2423b8609815b4f645dd3a54901d8c6068f1d1f11f957dbb5553dc468ea987a35b63adee5587bb16c2d94eba57

test:
  secret_key_base: bce0a4b003d8fc1660d65736c119cb569a51bad2e3449d2e6b8c955f0a4e264d407dea9995dc7bae020aebd887edfbd555a8e392dd0bd778a918497b6deab4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
